# Generated by Django 3.2 on 2021-05-04 04:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='files/2021-05-04/')),
                ('code', models.CharField(default=api.models.unique_code, max_length=10)),
            ],
        ),
    ]
